spring:
  application:
    name: manage
  datasource:
    url: jdbc:mysql://${SPRING-CLOUD-MYSQL-HOST}:3306/design?useSSL=false&characterEncoding=utf-8&useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8031
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${SPRING-CLOUD-EUREKA-ZONE}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
